[package]
name = "bend"
version = "0.1.0"
edition = "2021"

[lib]
name = "bend"
path = "src/lib.rs"

[[bin]]
name = "bend"
path = "src/main.rs"
required-features = ["cli"]

[profile.release]
lto = true

[features]
default = ["cli"]
cli = ["dep:clap"]

[dependencies]
TSPL = { git = "https://github.com/developedby/TSPL.git", branch = "fix-hvml-bugs" }
clap = { version = "4.4.1", features = ["derive"], optional = true }
highlight_error = "0.1.1"
hvm-core = { git = "https://github.com/HigherOrderCO/hvm-core.git", branch = "hvm32-compat" }
indexmap = "2.2.3"
interner = "0.2.1"
itertools = "0.11.0"
loaned = "0.1.0"
parking_lot = "0.12.1"
stacker = "0.1"
bpm = { git = "https://github.com/LunaAmora/Bend-Package-Manager" }
rpassword = "7.3"

[dev-dependencies]
insta = "1.34.0"
stdext = "0.3.1"
walkdir = "2.3.3"

[profile.test]
opt-level = 2
